#######################################################################
# Build maint-guide
# vim: set ts=8:
#######################################################################
### key adjustable parameters
#######################################################################
# languages translated with PO files
LANGPO	:=	ca de es fr it ja ru zh-cn zh-tw

#######################################################################
# $ make merge       # merge po1 and po2 data into po
#######################################################################
merge: $(addprefix po/, $(addsuffix .po, $(LANGPO)))

po/%.po: po1/%.po po2/%.po
	msgcat -u --use-first po1/$*.po po2/$*.po >po/$*.po

