#######################################################################
# Build maint-guide
# vim: set ts=8:
#######################################################################
### key adjustable parameters
#######################################################################
# languages translated with PO files
LANGPO	:=	ca de es fr it ja ru zh-cn zh-tw

#######################################################################
# $ make merge       # merge po1 and po2 data into po
#######################################################################
merge: $(addprefix po/, $(addsuffix .po, $(LANGPO)))

# po1 has priority over po2
po/%.po: po1/%.po po2/%.po
	msgcat po1/$*.po po2/$*.po |\
	msguniq --use-first >po/$*.po

